kind: pipeline
name: default

steps:

- name: sync_github_master
  image: usoft/protoc-gen-doc:3.6.1
  commands:
  - git remote add github git@github.com:usoft-china/usoft-sdk-b2b-csharp.git /usoft-sdk-b2b-csharp
  - cd usoft-sdk-b2b-csharp/bin/Debug
  - /bin/tar -cvf /usoft-sdk-b2b-csharp/dll-release/usoft-sdk-b2b-csharp.tar *.*
  - /git_commit.sh /usoft-sdk-b2b-csharp
  - cd /usoft-sdk-b2b-csharp
  - git push github master:master
  when:
    branch:
    - master
    event:
    - push    

- name: notify_email
  image: drillster/drone-email
  settings:
    host: smtp.mxhichina.com
    port: 25
    username: alert@usoftchina.com
    password: Mall1234567890
    from: alert@usoftchina.com
  when:
    branch:
    - develop
    - master
    status:
    - success
    - failure